// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMpEgPOyV8QM-mEkwr-ZImvQjPzTO5TTI',
    appId: '1:1090980332983:web:a49bafc10f5960ffc09432',
    messagingSenderId: '1090980332983',
    projectId: 'se7ety-mina',
    authDomain: 'se7ety-mina.firebaseapp.com',
    storageBucket: 'se7ety-mina.firebasestorage.app',
    measurementId: 'G-V8J8EMB0P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8JTwzBI0T4x9NYXmzr9IMiha6Ty9-JQs',
    appId: '1:862451983205:android:6ee4ea38427c5abd2a378c',
    messagingSenderId: '862451983205',
    projectId: 'se7ety-342',
    storageBucket: 'se7ety-342.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-AUyjo0vS2UYCtMJju0mSgsaX4Dkffo',
    appId: '1:862451983205:ios:462f12c2cd452c9b2a378c',
    messagingSenderId: '862451983205',
    projectId: 'se7ety-342',
    storageBucket: 'se7ety-342.firebasestorage.app',
    iosBundleId: 'com.eraasoft.se7ety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06ZeVqwDcJ4jf6umgwzs8L6S9TkgG5hc',
    appId: '1:1090980332983:ios:5ec6d7f2b1a77e52c09432',
    messagingSenderId: '1090980332983',
    projectId: 'se7ety-mina',
    storageBucket: 'se7ety-mina.firebasestorage.app',
    iosBundleId: 'com.eraasoft.se7ety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMpEgPOyV8QM-mEkwr-ZImvQjPzTO5TTI',
    appId: '1:1090980332983:web:ce3727287c15bee1c09432',
    messagingSenderId: '1090980332983',
    projectId: 'se7ety-mina',
    authDomain: 'se7ety-mina.firebaseapp.com',
    storageBucket: 'se7ety-mina.firebasestorage.app',
    measurementId: 'G-5SLJZN7XEH',
  );
}
